# Tp03 : Étude de cas Yelp

---

## Création du Dataset

### Import des librairie

In [249]:
import pandas as pd
from pandas import read_csv, DataFrame
import numpy as np
from utils import create_data_path

### Variable

In [250]:
data_set_path: dict[str, str] = {
    "avis"         : create_data_path("avis.csv"),
    "categories"   : create_data_path("categories.csv"),
    "checkin"      : create_data_path("checkin.csv"),
    "conseils"     : create_data_path("conseils.csv"),
    "horaires"     : create_data_path("horaires.csv"),
    "restaurants"  : create_data_path("restaurants.csv"),
    "services"     : create_data_path("services.csv"),
    "utilisateurs" : create_data_path("utilisateurs.csv")
}

/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3

### Charger Dataset

In [251]:
df_avis         = read_csv(data_set_path["avis"], skipinitialspace=True)
df_categories   = read_csv(data_set_path["categories"], skipinitialspace=True)
df_checking     = read_csv(data_set_path["checkin"], skipinitialspace=True)
df_conseils     = read_csv(data_set_path["conseils"], skipinitialspace=True)
df_horaires     = read_csv(data_set_path["horaires"], skipinitialspace=True)
df_restaurants  = read_csv(data_set_path["restaurants"], skipinitialspace=True)
df_services     = read_csv(data_set_path["services"], skipinitialspace=True)
df_utilisateurs = read_csv(data_set_path["utilisateurs"], skipinitialspace=True)

---

### Information sur les Dataset

| Fichier      | Information du fichier            |
|--------------|-----------------------------------|
| avis         | etoile, utile                     |
| categories   | categories pour les restaurants   |
| checkin      | rentrer des personnes             |
| conseil      | nombre de compliment              |
| horaire      | horaire des différent restaurant  |
| restaurant   | nom, ville, moyenne étoile, ferme |
| service      | les choses qu'il font             |
| utilisateurs | information sur l'utilisateur     |

---

# Nettoyage des données

## Avis

### Vérifications :

In [252]:
# Vérification des colonnes
df_avis

,avis_id,utilisateur_id,restaurant_id,etoiles,useful,funny,cool,date
0,yi0R0Ugj_xUx_Nek0-_Qig,dacAIZ6fTM6mqwW5uxkskg,ikCg8xy5JIg_NGPx-MSIDA,5.0,0,0,0,2018-01-09 20:56:38
1,8e9HxxLjjqc9ez5ezzN7iQ,d6xvYpyzcfbF_AZ8vMB7QA,zvO-PJCpNk4fgAVUnExYAA,1.0,3,1,1,2010-10-05 19:12:35
2,Z7wgXp98wYB57QdRY3HQ3w,GYNnVehQeXjty0xH7-6Fhw,FxLfqxdYPA6Z85PFKaqLrg,4.0,0,0,0,2016-05-07 01:36:53
3,JVcjMhlavKKn3UIt9p9OXA,TpyOT5E16YASd7EWjLQlrw,AakkkTuGZA2KBodKi2_u8A,1.0,1,1,0,2012-07-16 00:37:14
4,6BnQwlxRn7ZuWdzninM9sQ,JSrP-dUmLlwZiI7Dp3PQ2A,cHdJXLlKNWixBXpDwEGb_A,3.0,1,7,1,2015-04-01 16:30:00
...,...,...,...,...,...,...,...,...
2073680,bzQFrsMDtGIVOeXp5gbNeg,g5K5E9QrxObn6ZC1q8Mb9g,CRVtzesMuwHK-phmS_ojaA,4.0,0,0,0,2012-03-29 23:35:45
2073681,0sf0k7p1b1krPfcbP62W5A,Ob6ToKjLna3WOZtrI_m0nw,t1P_vLIyJCIoEaUVcwHdTw,1.0,2,1,1,2013-09-21 18:14:30
2073682,jPCXuSBbI_cPocgoNBhdkg,V6BjjQICDO4q7TT3ZhaPWw,yA6dKNm_zl1ucZCnwW8ZCg,1.0,13,11,5,2013-05-22 15:32:08
2073683,zwzO3yPdGbdgGy3-XQ0SWg,PFiIECX8wuvi7P-1mCvIjA,a192hdM0_UVCYLwPJv1Qwg,5.0,0,0,0,2018-11-13 21:15:20
2073684,OKmOLFwtI-NjofTHAGzv1Q,Ej3mCvjcwVXCSPB_avIfjQ,PkqN5st3zZ_Xce_5QlBtNQ,3.0,2,0,0,2018-11-12 20:25:32

In [253]:
# Vérification des types
df_avis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073685 entries, 0 to 2073684
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   avis_id         object
 1   utilisateur_id  object
 2   restaurant_id   object
 3   etoiles         float64
 4   useful          int64
 5   funny           int64
 6   cool            int64
 7   date            object
dtypes: float64(1), int64(3), object(4)
memory usage: 126.6+ MB

In [254]:
# Vérification rapide
df_avis.describe(include="all")

# Tous des ID d'avis uniques

,avis_id,utilisateur_id,restaurant_id,etoiles,useful,funny,cool,date
count,2073685,2073685,2073685,2.073685e+06,2.073685e+06,2.073685e+06,2.073685e+06,2073685
unique,2073685,748247,34268,NaN,NaN,NaN,NaN,2061506
top,yi0R0Ugj_xUx_Nek0-_Qig,CxDOIDnH8gp9KXzpBHJYXw,K7lWdNUhCbcnEvI0NhGewg,NaN,NaN,NaN,NaN,2014-07-28 05:36:33
freq,1,1618,6887,NaN,NaN,NaN,NaN,5
mean,NaN,NaN,NaN,3.682247e+00,1.167306e+00,4.797759e-01,5.875266e-01,NaN
std,NaN,NaN,NaN,1.376978e+00,3.909121e+00,2.967384e+00,2.336469e+00,NaN
min,NaN,NaN,NaN,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
25%,NaN,NaN,NaN,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
50%,NaN,NaN,NaN,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
75%,NaN,NaN,NaN,5.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,NaN
max,NaN,NaN,NaN,5.000000e+00,1.241000e+03,1.290000e+03,5.060000e+02,NaN

In [255]:
# Vérification des données manquantes
df_avis.isna().sum()

avis_id           0
utilisateur_id    0
restaurant_id     0
etoiles           0
useful            0
funny             0
cool              0
date              0
dtype: int64

In [256]:
# Vérification si le nombre d'étoiles est bien entre 1 et 5
df_avis[(df_avis['etoiles'] < 1) & (df_avis['etoiles'] > 5)]

Empty DataFrame
Columns: [avis_id, utilisateur_id, restaurant_id, etoiles, useful, funny, cool, date]
Index: []

In [257]:
# Verification s'il existe des nombres négatifs
df_avis[(df_avis['useful'] < 0) & (df_avis['funny'] < 0) & (df_avis['cool'] < 0)]

Empty DataFrame
Columns: [avis_id, utilisateur_id, restaurant_id, etoiles, useful, funny, cool, date]
Index: []

### Nettoyages :

In [258]:
# Conversion vers les types appropriés
df_avis["avis_id"] = df_avis["avis_id"].astype("string")
df_avis["restaurant_id"] = df_avis["restaurant_id"].astype("string")
df_avis["utilisateur_id"] = df_avis["utilisateur_id"].astype("string")
df_avis["etoiles"] = df_avis["etoiles"].astype("int64")
df_avis['date'] = pd.to_datetime(df_avis['date'], errors='coerce')
df_avis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073685 entries, 0 to 2073684
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   avis_id         string
 1   utilisateur_id  string
 2   restaurant_id   string
 3   etoiles         int64
 4   useful          int64
 5   funny           int64
 6   cool            int64
 7   date            datetime64[ns]
dtypes: datetime64[ns](1), int64(4), string(3)
memory usage: 126.6 MB

In [259]:
# Vérification s'il n'y a pas de dates invalides
df_avis['date'].isna().sum()

np.int64(0)

### Dataset nettoyé :

In [260]:
df_avis

,avis_id,utilisateur_id,restaurant_id,etoiles,useful,funny,cool,date
0,yi0R0Ugj_xUx_Nek0-_Qig,dacAIZ6fTM6mqwW5uxkskg,ikCg8xy5JIg_NGPx-MSIDA,5,0,0,0,2018-01-09 20:56:38
1,8e9HxxLjjqc9ez5ezzN7iQ,d6xvYpyzcfbF_AZ8vMB7QA,zvO-PJCpNk4fgAVUnExYAA,1,3,1,1,2010-10-05 19:12:35
2,Z7wgXp98wYB57QdRY3HQ3w,GYNnVehQeXjty0xH7-6Fhw,FxLfqxdYPA6Z85PFKaqLrg,4,0,0,0,2016-05-07 01:36:53
3,JVcjMhlavKKn3UIt9p9OXA,TpyOT5E16YASd7EWjLQlrw,AakkkTuGZA2KBodKi2_u8A,1,1,1,0,2012-07-16 00:37:14
4,6BnQwlxRn7ZuWdzninM9sQ,JSrP-dUmLlwZiI7Dp3PQ2A,cHdJXLlKNWixBXpDwEGb_A,3,1,7,1,2015-04-01 16:30:00
...,...,...,...,...,...,...,...,...
2073680,bzQFrsMDtGIVOeXp5gbNeg,g5K5E9QrxObn6ZC1q8Mb9g,CRVtzesMuwHK-phmS_ojaA,4,0,0,0,2012-03-29 23:35:45
2073681,0sf0k7p1b1krPfcbP62W5A,Ob6ToKjLna3WOZtrI_m0nw,t1P_vLIyJCIoEaUVcwHdTw,1,2,1,1,2013-09-21 18:14:30
2073682,jPCXuSBbI_cPocgoNBhdkg,V6BjjQICDO4q7TT3ZhaPWw,yA6dKNm_zl1ucZCnwW8ZCg,1,13,11,5,2013-05-22 15:32:08
2073683,zwzO3yPdGbdgGy3-XQ0SWg,PFiIECX8wuvi7P-1mCvIjA,a192hdM0_UVCYLwPJv1Qwg,5,0,0,0,2018-11-13 21:15:20
2073684,OKmOLFwtI-NjofTHAGzv1Q,Ej3mCvjcwVXCSPB_avIfjQ,PkqN5st3zZ_Xce_5QlBtNQ,3,2,0,0,2018-11-12 20:25:32

---

## Utilisateurs

### Vérifications :

In [261]:
# Vérification des colonnes
df_utilisateurs

                utilisateur_id       nom  elite  nb_avis  nb_avis_mention
0       l6BmjZMeQD3rDxWUbiAiow    Rashmi      1       95               84
1       4XChL029mKr5hydo79Ljxg     Jenna      0       33               48
2       bc8C_eETBWL0olvFSJJd0w     David      0       16               28
3       MM4RJAeH6yuaN8oZDSt0RA     Nancy      1      361             1114
4       TEtzbpgA2BFBrC0y0sCbfw     Keane      1     1122            13311
...                        ...       ...    ...      ...              ...
748242  qIKRzgQwcLsRbcjFYD1jkg      Joel      0        3                0
748243  vyK8txmse-HVk7hAKCvuMQ     Keith      0       10                4
748244  gCfFBY-cO1Y0TxxKX89-ig  Maryorie      0        1                0
748245  Z2uEg8DIk1twiNC6NV7e9w   Adriana      0        1                1
748246  ib_elCBhGOamS0AALkh4Og       Lee      0        4                8

[748247 rows x 5 columns]

In [262]:
# Vérification des types
df_utilisateurs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748247 entries, 0 to 748246
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   utilisateur_id   748247 non-null  object
 1   nom              748239 non-null  object
 2   elite            748247 non-null  int64
 3   nb_avis          748247 non-null  int64
 4   nb_avis_mention  748247 non-null  int64
dtypes: int64(3), object(2)
memory usage: 28.5+ MB

In [263]:
# Vérification rapide
df_utilisateurs.describe(include="all")

# Tous des ID Uniques
# Minimum de 0 et maximum de 1 pour elite
# Aucun nombre négatif

,utilisateur_id,nom,elite,nb_avis,nb_avis_mention
count,748247,748239,748247.000000,748247.00000,748247.000000
unique,748247,72126,NaN,NaN,NaN
top,l6BmjZMeQD3rDxWUbiAiow,John,NaN,NaN,NaN
freq,1,6668,NaN,NaN,NaN
mean,NaN,NaN,0.072799,34.38974,67.922637
std,NaN,NaN,0.259807,105.32548,667.026047
min,NaN,NaN,0.000000,0.00000,0.000000
25%,NaN,NaN,0.000000,3.00000,1.000000
50%,NaN,NaN,0.000000,9.00000,5.000000
75%,NaN,NaN,0.000000,24.00000,22.000000
max,NaN,NaN,1.000000,13278.00000,154202.000000

In [264]:
# Vérification des données manquantes
df_utilisateurs.isna().sum()

utilisateur_id     0
nom                8
elite              0
nb_avis            0
nb_avis_mention    0
dtype: int64

In [265]:
# Vérification s'il existe des données autres que 1 ou 0
df_utilisateurs[(df_utilisateurs['elite'] != 1) & (df_utilisateurs['elite'] != 0)]

Empty DataFrame
Columns: [utilisateur_id, nom, elite, nb_avis, nb_avis_mention]
Index: []

In [266]:
# Vérification s'il existe des nombres négatifs
df_utilisateurs[df_utilisateurs["nb_avis"] < 0]

Empty DataFrame
Columns: [utilisateur_id, nom, elite, nb_avis, nb_avis_mention]
Index: []

In [267]:
# Vérification s'il existe des nombres négatifs
df_utilisateurs[df_utilisateurs["nb_avis_mention"] < 0]

Empty DataFrame
Columns: [utilisateur_id, nom, elite, nb_avis, nb_avis_mention]
Index: []

In [268]:
# Vérification s'il existe un ID dupliqué
df_utilisateurs["utilisateur_id"].duplicated().sum()

np.int64(0)

### Nettoyages :

In [269]:
# Même si les noms sont manquants, on a les IDs et le nombre d'avis
df_utilisateurs['nom'] = df_utilisateurs['nom'].fillna('Inconnu')
df_utilisateurs[df_utilisateurs['nom'] == 'Inconnu']

                utilisateur_id      nom  elite  nb_avis  nb_avis_mention
87688   GiReVCFFK4WuhocoxDmOvw  Inconnu      0        5                0
161155  aahxmN1tsvlufuU_y4OT1A  Inconnu      0       23               61
207141  UgeQ4jZUvh8aknnOmvKRwg  Inconnu      0        9               11
237770  7UlRHLbYWR7RrIOp1pHDjw  Inconnu      1      486              945
245555  degkhE1YTY9x3Vt2OMEZbw  Inconnu      0       15               10
288643  OmBde8IjHEcO0QwS_jl5sA  Inconnu      0        9                3
369701  UxQyVv6m5N0Eb2hBp7VDqw  Inconnu      0        4                0
519971  nLJJAZM8CPA3W56cpZ9gxw  Inconnu      0        3                6

In [270]:
# Conversion des entiers (0, 1) en booléens
df_utilisateurs['elite'] = df_utilisateurs['elite'].astype(bool)
df_utilisateurs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748247 entries, 0 to 748246
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   utilisateur_id   748247 non-null  object
 1   nom              748247 non-null  object
 2   elite            748247 non-null  bool
 3   nb_avis          748247 non-null  int64
 4   nb_avis_mention  748247 non-null  int64
dtypes: bool(1), int64(2), object(2)
memory usage: 23.5+ MB

### Dataset nettoyé :

In [271]:
df_utilisateurs

                utilisateur_id       nom  elite  nb_avis  nb_avis_mention
0       l6BmjZMeQD3rDxWUbiAiow    Rashmi   True       95               84
1       4XChL029mKr5hydo79Ljxg     Jenna  False       33               48
2       bc8C_eETBWL0olvFSJJd0w     David  False       16               28
3       MM4RJAeH6yuaN8oZDSt0RA     Nancy   True      361             1114
4       TEtzbpgA2BFBrC0y0sCbfw     Keane   True     1122            13311
...                        ...       ...    ...      ...              ...
748242  qIKRzgQwcLsRbcjFYD1jkg      Joel  False        3                0
748243  vyK8txmse-HVk7hAKCvuMQ     Keith  False       10                4
748244  gCfFBY-cO1Y0TxxKX89-ig  Maryorie  False        1                0
748245  Z2uEg8DIk1twiNC6NV7e9w   Adriana  False        1                1
748246  ib_elCBhGOamS0AALkh4Og       Lee  False        4                8

[748247 rows x 5 columns]

---