# Tp03 : Étude de cas Yelp

---

## Préparations

### Import des librairie

In [1678]:
import pandas as pd
from pandas import read_csv, DataFrame
import numpy as np
from utils import create_data_path

### Variable du path

In [1679]:
data_set_path: dict[str, str] = {
    'avis'         : create_data_path('avis.csv'),
    'categories'   : create_data_path('categories.csv'),
    'checkin'      : create_data_path('checkin.csv'),
    'conseils'     : create_data_path('conseils.csv'),
    'horaires'     : create_data_path('horaires.csv'),
    'restaurants'  : create_data_path('restaurants.csv'),
    'services'     : create_data_path('services.csv'),
    'utilisateurs' : create_data_path('utilisateurs.csv')
}

/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3
/home/dewk/Code/collecte/tp3

### Charger les tables en Datasets

In [1680]:
df_avis         = read_csv(data_set_path['avis'], skipinitialspace=True)
df_categories   = read_csv(data_set_path['categories'], skipinitialspace=True)
df_checkin      = read_csv(data_set_path['checkin'], skipinitialspace=True)
df_conseils     = read_csv(data_set_path['conseils'], skipinitialspace=True)
df_horaires     = read_csv(data_set_path['horaires'], skipinitialspace=True)
df_restaurants  = read_csv(data_set_path['restaurants'], skipinitialspace=True)
df_services     = read_csv(data_set_path['services'], skipinitialspace=True)
df_utilisateurs = read_csv(data_set_path['utilisateurs'], skipinitialspace=True)

---

## Informations sur les tables

| Fichier      | Informations du fichier           |
|--------------|-----------------------------------|
| avis         | étoile, utile                     |
| categories   | catégories pour les restaurants   |
| checkin      | entrées des personnes             |
| conseils     | nombre de compliments             |
| horaires     | horaire des différents restaurants|
| restaurants  | nom, ville, moyenne étoile, ferme |
| services     | les choses qu'ils font            |
| utilisateurs | informations sur l'utilisateur    |

---

# Nettoyage des Datasets

## Avis

### Vérifications :

In [1681]:
# Vérification des colonnes
df_avis

,avis_id,utilisateur_id,restaurant_id,etoiles,useful,funny,cool,date
0,yi0R0Ugj_xUx_Nek0-_Qig,dacAIZ6fTM6mqwW5uxkskg,ikCg8xy5JIg_NGPx-MSIDA,5.0,0,0,0,2018-01-09 20:56:38
1,8e9HxxLjjqc9ez5ezzN7iQ,d6xvYpyzcfbF_AZ8vMB7QA,zvO-PJCpNk4fgAVUnExYAA,1.0,3,1,1,2010-10-05 19:12:35
2,Z7wgXp98wYB57QdRY3HQ3w,GYNnVehQeXjty0xH7-6Fhw,FxLfqxdYPA6Z85PFKaqLrg,4.0,0,0,0,2016-05-07 01:36:53
3,JVcjMhlavKKn3UIt9p9OXA,TpyOT5E16YASd7EWjLQlrw,AakkkTuGZA2KBodKi2_u8A,1.0,1,1,0,2012-07-16 00:37:14
4,6BnQwlxRn7ZuWdzninM9sQ,JSrP-dUmLlwZiI7Dp3PQ2A,cHdJXLlKNWixBXpDwEGb_A,3.0,1,7,1,2015-04-01 16:30:00
...,...,...,...,...,...,...,...,...
2073680,bzQFrsMDtGIVOeXp5gbNeg,g5K5E9QrxObn6ZC1q8Mb9g,CRVtzesMuwHK-phmS_ojaA,4.0,0,0,0,2012-03-29 23:35:45
2073681,0sf0k7p1b1krPfcbP62W5A,Ob6ToKjLna3WOZtrI_m0nw,t1P_vLIyJCIoEaUVcwHdTw,1.0,2,1,1,2013-09-21 18:14:30
2073682,jPCXuSBbI_cPocgoNBhdkg,V6BjjQICDO4q7TT3ZhaPWw,yA6dKNm_zl1ucZCnwW8ZCg,1.0,13,11,5,2013-05-22 15:32:08
2073683,zwzO3yPdGbdgGy3-XQ0SWg,PFiIECX8wuvi7P-1mCvIjA,a192hdM0_UVCYLwPJv1Qwg,5.0,0,0,0,2018-11-13 21:15:20
2073684,OKmOLFwtI-NjofTHAGzv1Q,Ej3mCvjcwVXCSPB_avIfjQ,PkqN5st3zZ_Xce_5QlBtNQ,3.0,2,0,0,2018-11-12 20:25:32

In [1682]:
# Vérification des types
df_avis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073685 entries, 0 to 2073684
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   avis_id         object
 1   utilisateur_id  object
 2   restaurant_id   object
 3   etoiles         float64
 4   useful          int64
 5   funny           int64
 6   cool            int64
 7   date            object
dtypes: float64(1), int64(3), object(4)
memory usage: 126.6+ MB

In [1683]:
# Vérification rapide
df_avis.describe(include='all')

# Tous des ID d'avis uniques

,avis_id,utilisateur_id,restaurant_id,etoiles,useful,funny,cool,date
count,2073685,2073685,2073685,2.073685e+06,2.073685e+06,2.073685e+06,2.073685e+06,2073685
unique,2073685,748247,34268,NaN,NaN,NaN,NaN,2061506
top,yi0R0Ugj_xUx_Nek0-_Qig,CxDOIDnH8gp9KXzpBHJYXw,K7lWdNUhCbcnEvI0NhGewg,NaN,NaN,NaN,NaN,2014-07-28 05:36:33
freq,1,1618,6887,NaN,NaN,NaN,NaN,5
mean,NaN,NaN,NaN,3.682247e+00,1.167306e+00,4.797759e-01,5.875266e-01,NaN
std,NaN,NaN,NaN,1.376978e+00,3.909121e+00,2.967384e+00,2.336469e+00,NaN
min,NaN,NaN,NaN,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
25%,NaN,NaN,NaN,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
50%,NaN,NaN,NaN,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
75%,NaN,NaN,NaN,5.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,NaN
max,NaN,NaN,NaN,5.000000e+00,1.241000e+03,1.290000e+03,5.060000e+02,NaN

In [1684]:
# Vérification des données manquantes
df_avis.isna().sum()

avis_id           0
utilisateur_id    0
restaurant_id     0
etoiles           0
useful            0
funny             0
cool              0
date              0
dtype: int64

In [1685]:
# Vérification s'il y a des strings vides
df_avis[(df_avis['avis_id'] == '') | (df_avis['utilisateur_id'] == '') | (df_avis['restaurant_id'] == '')]

Empty DataFrame
Columns: [avis_id, utilisateur_id, restaurant_id, etoiles, useful, funny, cool, date]
Index: []

In [1686]:
# Vérification si le nombre d'étoiles est bien entre 1 et 5
df_avis[(df_avis['etoiles'] < 1) & (df_avis['etoiles'] > 5)]

Empty DataFrame
Columns: [avis_id, utilisateur_id, restaurant_id, etoiles, useful, funny, cool, date]
Index: []

In [1687]:
# Verification s'il existe des nombres négatifs
df_avis[(df_avis['useful'] < 0) & (df_avis['funny'] < 0) & (df_avis['cool'] < 0)]

Empty DataFrame
Columns: [avis_id, utilisateur_id, restaurant_id, etoiles, useful, funny, cool, date]
Index: []

### Nettoyages :

In [1688]:
# Conversion vers les types appropriés
df_avis['avis_id'] = df_avis['avis_id'].astype('string')
df_avis['restaurant_id'] = df_avis['restaurant_id'].astype('string')
df_avis['utilisateur_id'] = df_avis['utilisateur_id'].astype('string')
df_avis['etoiles'] = df_avis['etoiles'].astype('int64')
df_avis['date'] = pd.to_datetime(df_avis['date'], errors='coerce')
df_avis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2073685 entries, 0 to 2073684
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   avis_id         string
 1   utilisateur_id  string
 2   restaurant_id   string
 3   etoiles         int64
 4   useful          int64
 5   funny           int64
 6   cool            int64
 7   date            datetime64[ns]
dtypes: datetime64[ns](1), int64(4), string(3)
memory usage: 126.6 MB

In [1689]:
# Vérification s'il n'y a pas de dates invalides
df_avis['date'].isna().sum()

np.int64(0)

In [1690]:
# Suppression des colonnes non-utilisées
df_avis = df_avis.drop(columns=['useful', 'funny', 'cool'])

### Dataset nettoyé :

In [1691]:
df_avis

,avis_id,utilisateur_id,restaurant_id,etoiles,date
0,yi0R0Ugj_xUx_Nek0-_Qig,dacAIZ6fTM6mqwW5uxkskg,ikCg8xy5JIg_NGPx-MSIDA,5,2018-01-09 20:56:38
1,8e9HxxLjjqc9ez5ezzN7iQ,d6xvYpyzcfbF_AZ8vMB7QA,zvO-PJCpNk4fgAVUnExYAA,1,2010-10-05 19:12:35
2,Z7wgXp98wYB57QdRY3HQ3w,GYNnVehQeXjty0xH7-6Fhw,FxLfqxdYPA6Z85PFKaqLrg,4,2016-05-07 01:36:53
3,JVcjMhlavKKn3UIt9p9OXA,TpyOT5E16YASd7EWjLQlrw,AakkkTuGZA2KBodKi2_u8A,1,2012-07-16 00:37:14
4,6BnQwlxRn7ZuWdzninM9sQ,JSrP-dUmLlwZiI7Dp3PQ2A,cHdJXLlKNWixBXpDwEGb_A,3,2015-04-01 16:30:00
...,...,...,...,...,...
2073680,bzQFrsMDtGIVOeXp5gbNeg,g5K5E9QrxObn6ZC1q8Mb9g,CRVtzesMuwHK-phmS_ojaA,4,2012-03-29 23:35:45
2073681,0sf0k7p1b1krPfcbP62W5A,Ob6ToKjLna3WOZtrI_m0nw,t1P_vLIyJCIoEaUVcwHdTw,1,2013-09-21 18:14:30
2073682,jPCXuSBbI_cPocgoNBhdkg,V6BjjQICDO4q7TT3ZhaPWw,yA6dKNm_zl1ucZCnwW8ZCg,1,2013-05-22 15:32:08
2073683,zwzO3yPdGbdgGy3-XQ0SWg,PFiIECX8wuvi7P-1mCvIjA,a192hdM0_UVCYLwPJv1Qwg,5,2018-11-13 21:15:20
2073684,OKmOLFwtI-NjofTHAGzv1Q,Ej3mCvjcwVXCSPB_avIfjQ,PkqN5st3zZ_Xce_5QlBtNQ,3,2018-11-12 20:25:32

---

## Categories

### Vérifications :

In [1692]:
df_categories

                restaurant_id               categorie
0      lCwqJWMxvIUQt1Re_tDn4w      Breakfast & Brunch
1      lCwqJWMxvIUQt1Re_tDn4w                  Diners
2      lCwqJWMxvIUQt1Re_tDn4w  American (Traditional)
3      pd0v6sOqpLhFJ7mkpIaixw              Sandwiches
4      pd0v6sOqpLhFJ7mkpIaixw             Gluten-Free
...                       ...                     ...
89940  7KlpgRjjAmVabPzxcExs0g                 Mexican
89941  0fY-zYyP2fDmp2YXFsuNTg              Sandwiches
89942  0fY-zYyP2fDmp2YXFsuNTg                    Soup
89943  0fY-zYyP2fDmp2YXFsuNTg                  Bagels
89944  cfrN6-lQC-dzjBtNBjefpQ          American (New)

[89945 rows x 2 columns]

In [1693]:
df_categories.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89945 entries, 0 to 89944
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   restaurant_id  89945 non-null  object
 1   categorie      89945 non-null  object
dtypes: object(2)
memory usage: 1.4+ MB

In [1694]:
df_categories.describe(include='all')

                 restaurant_id  categorie
count                    89945      89945
unique                   33816        626
top     QSwpHbPjDhWYKP8qlmlkXg  Nightlife
freq                        23       4827

In [1695]:
df_categories[df_categories.duplicated(subset=['restaurant_id', 'categorie'], keep=False)]
    # Doublon trouvé

                restaurant_id     categorie
26944  mlkVAm2DkGnKnNVR1AnQLA  Gas Stations
26947  mlkVAm2DkGnKnNVR1AnQLA  Gas Stations

In [1696]:
df_categories.isna().sum()

restaurant_id    0
categorie        0
dtype: int64

In [1697]:
# Vérification s'il y a des strings vides
df_categories[(df_categories['categorie'] == '') | (df_categories['restaurant_id'] == '')]

Empty DataFrame
Columns: [restaurant_id, categorie]
Index: []

### Nettoyage :

In [1698]:
# Suppression du doublon
df_categories = df_categories.drop_duplicates(subset=['restaurant_id', 'categorie']).copy()
df_categories[df_categories.duplicated(subset=['restaurant_id', 'categorie'], keep=False)]

Empty DataFrame
Columns: [restaurant_id, categorie]
Index: []

In [1699]:
# Conversion vers les types appropriés
df_categories['restaurant_id'] = df_categories['restaurant_id'].astype('string')
df_categories['categorie'] = df_categories['categorie'].astype('string')
df_categories.info()

<class 'pandas.core.frame.DataFrame'>
Index: 89944 entries, 0 to 89944
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   restaurant_id  89944 non-null  string
 1   categorie      89944 non-null  string
dtypes: string(2)
memory usage: 2.1 MB

### Dataset nettoyé :

In [1700]:
df_categories

                restaurant_id               categorie
0      lCwqJWMxvIUQt1Re_tDn4w      Breakfast & Brunch
1      lCwqJWMxvIUQt1Re_tDn4w                  Diners
2      lCwqJWMxvIUQt1Re_tDn4w  American (Traditional)
3      pd0v6sOqpLhFJ7mkpIaixw              Sandwiches
4      pd0v6sOqpLhFJ7mkpIaixw             Gluten-Free
...                       ...                     ...
89940  7KlpgRjjAmVabPzxcExs0g                 Mexican
89941  0fY-zYyP2fDmp2YXFsuNTg              Sandwiches
89942  0fY-zYyP2fDmp2YXFsuNTg                    Soup
89943  0fY-zYyP2fDmp2YXFsuNTg                  Bagels
89944  cfrN6-lQC-dzjBtNBjefpQ          American (New)

[89944 rows x 2 columns]

---

## Check-in

### Vérifications :

In [1701]:
df_checkin

                  restaurant_id                 date
0        --1UhMGODdWsrMastO9DZw  2016-04-26 19:49:16
1        --1UhMGODdWsrMastO9DZw  2016-08-30 18:36:57
2        --1UhMGODdWsrMastO9DZw  2016-10-15 02:45:18
3        --1UhMGODdWsrMastO9DZw  2016-11-18 01:54:50
4        --1UhMGODdWsrMastO9DZw  2017-04-20 18:39:06
...                         ...                  ...
5492277  zzzaIBwimxVej4tY6qFOUQ  2014-07-04 21:28:29
5492278  zzzaIBwimxVej4tY6qFOUQ  2014-07-14 01:02:55
5492279  zzzaIBwimxVej4tY6qFOUQ  2014-07-14 21:26:59
5492280  zzzaIBwimxVej4tY6qFOUQ  2014-07-17 01:06:02
5492281  zzzaIBwimxVej4tY6qFOUQ  2014-07-17 19:20:28

[5492282 rows x 2 columns]

In [1702]:
df_checkin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5492282 entries, 0 to 5492281
Data columns (total 2 columns):
 #   Column         Dtype
---  ------         -----
 0   restaurant_id  object
 1   date           object
dtypes: object(2)
memory usage: 83.8+ MB

In [1703]:
df_checkin.describe(include='all')

                 restaurant_id                 date
count                  5492282              5492282
unique                   32831              5390249
top     DkYS3arLOhA8si5uUEmHOw  2013-12-26 22:01:42
freq                     25835                    4

In [1704]:
df_checkin[df_checkin['date'] == '2013-12-26 22:01:42']
    # Pas le même restaurant, ne sont donc pas des doublons

                  restaurant_id                 date
1061257  BnpuVvPy3sfLlkqKCx6Xnw  2013-12-26 22:01:42
1287581  DwS5_jKur2mfxvqDp_gptg  2013-12-26 22:01:42
1608572  HnbkGxUs7oWKYDeB-Pk82Q  2013-12-26 22:01:42
2146208  NXNa5OYmN1CNmXwHhDxpRA  2013-12-26 22:01:42

In [1705]:
df_checkin.isna().sum()

restaurant_id    0
date             0
dtype: int64

In [1706]:
# Vérification s'il y a des strings vides
df_checkin[(df_checkin['restaurant_id'] == '')]

Empty DataFrame
Columns: [restaurant_id, date]
Index: []

### Nettoyage :

In [1707]:
# Conversion vers les types appropriés
df_checkin['restaurant_id'] = df_checkin['restaurant_id'].astype('string')
df_checkin['date'] = pd.to_datetime(df_checkin['date'], errors='coerce')
df_checkin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5492282 entries, 0 to 5492281
Data columns (total 2 columns):
 #   Column         Dtype
---  ------         -----
 0   restaurant_id  string
 1   date           datetime64[ns]
dtypes: datetime64[ns](1), string(1)
memory usage: 83.8 MB

### Dataset nettoyé :

In [1708]:
df_checkin

                  restaurant_id                date
0        --1UhMGODdWsrMastO9DZw 2016-04-26 19:49:16
1        --1UhMGODdWsrMastO9DZw 2016-08-30 18:36:57
2        --1UhMGODdWsrMastO9DZw 2016-10-15 02:45:18
3        --1UhMGODdWsrMastO9DZw 2016-11-18 01:54:50
4        --1UhMGODdWsrMastO9DZw 2017-04-20 18:39:06
...                         ...                 ...
5492277  zzzaIBwimxVej4tY6qFOUQ 2014-07-04 21:28:29
5492278  zzzaIBwimxVej4tY6qFOUQ 2014-07-14 01:02:55
5492279  zzzaIBwimxVej4tY6qFOUQ 2014-07-14 21:26:59
5492280  zzzaIBwimxVej4tY6qFOUQ 2014-07-17 01:06:02
5492281  zzzaIBwimxVej4tY6qFOUQ 2014-07-17 19:20:28

[5492282 rows x 2 columns]

---

## Conseils

### Vérifications :

In [1709]:
df_conseils

,utilisateur_id,restaurant_id,nb_compliments,date
0,UPw5DWs_b-e2JRBS-t37Ag,VaKXUpmWTTWDKbpJ3aQdMw,0,2014-03-27 03:51:24
1,jRyO2V1pA4CdVVqCIOPc1Q,5KheTjYPu1HcQzQFtm4_vw,0,2011-12-26 01:46:17
2,FuTJWFYm4UKqewaosss1KA,TkoyGi8J7YFjA6SbaRzrxg,0,2014-03-23 21:32:49
3,CaFbX7topxdLpBJ_SNDfGQ,r49iBfbnfoK7yt4rdsL_7g,0,2016-01-05 06:39:33
4,8zXgNCkusOHMwh5Tj_8yCQ,qrSsS0pk7SL67MP5nN8tlg,0,2013-12-22 05:10:12
...,...,...,...,...
416798,yx_38-qpzJU2Oqb5P3QBqA,ZeeWNTA3wpabS_0Y1We7DA,0,2018-05-07 18:32:24
416799,Lu7d-uVVEYZrmxtX0gI8hQ,3GEEy7RP6e4bT4LAiWFMFQ,0,2018-05-16 14:47:50
416800,cHaCQ03WO3OWNmySffQprw,y-ZZe1dz8AMjiAwNVo3h_A,0,2018-06-26 22:14:05
416801,mkbx55W8B8aPLgDqex7qgg,OMRYQihVjqqzjoNoQgyhgQ,2,2017-11-10 15:34:58
416802,T4R5ZKfcGt1GIAgjCh67eA,n5Hc_iMVkyxcS0SXiBCbOQ,0,2018-10-13 16:57:50

In [1710]:
df_conseils.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 416803 entries, 0 to 416802
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   utilisateur_id  416803 non-null  object
 1   restaurant_id   416803 non-null  object
 2   nb_compliments  416803 non-null  int64
 3   date            416803 non-null  object
dtypes: int64(1), object(3)
memory usage: 12.7+ MB

In [1711]:
df_conseils.describe(include='all')
    # Pas de compliments négatifs

,utilisateur_id,restaurant_id,nb_compliments,date
count,416803,416803,416803.000000,416803
unique,156743,28827,NaN,416187
top,mkbx55W8B8aPLgDqex7qgg,DkYS3arLOhA8si5uUEmHOw,NaN,2017-07-29 02:22:28
freq,743,1503,NaN,3
mean,NaN,NaN,0.015852,NaN
std,NaN,NaN,0.141101,NaN
min,NaN,NaN,0.000000,NaN
25%,NaN,NaN,0.000000,NaN
50%,NaN,NaN,0.000000,NaN
75%,NaN,NaN,0.000000,NaN
max,NaN,NaN,9.000000,NaN

In [1712]:
df_conseils[df_conseils['date'] == '2017-07-29 02:22:28']

,utilisateur_id,restaurant_id,nb_compliments,date
194070,ZKt3JdtmIRdcQI7piOZ18g,MgSd4P3ATkiywbbraFygHg,0,2017-07-29 02:22:28
213089,ZKt3JdtmIRdcQI7piOZ18g,MgSd4P3ATkiywbbraFygHg,0,2017-07-29 02:22:28
216507,ZKt3JdtmIRdcQI7piOZ18g,MgSd4P3ATkiywbbraFygHg,0,2017-07-29 02:22:28

In [1713]:
df_conseils[df_conseils['date'].duplicated()]

,utilisateur_id,restaurant_id,nb_compliments,date
6065,zpnDr3EBaVU8QPNHE3eDbg,I6u-OhmI_IUltexEOSCKzg,0,2011-10-06 23:30:29
6805,ia5kvJxYR8gPItl9O4W0Mg,7JR42RkKub9bsBSeXfAjew,0,2015-01-19 01:11:12
7559,rpWCcNQD7nGVUYoU6vzCFw,2UaMR7lOJ3IcXizaDpv7KA,0,2011-10-08 04:15:19
13095,ghwqimFsDVMEUOYVDTdmxg,3GEEy7RP6e4bT4LAiWFMFQ,0,2014-06-20 01:26:10
18329,ZfZCj9pT54yYSRwlzr4CKQ,Q194SAY2nwnSZ18c0oBvDg,0,2012-03-29 22:18:01
...,...,...,...,...
414739,WeqG_Kg7W9REJ8KtjNq_OQ,xKhjhko44Wr7IjMLnsV43g,0,2018-06-15 04:11:01
414933,lddmAHba81zPOUuBmNi3iA,iwzVhM5CirzkNS5wTxwZeA,0,2014-02-22 02:15:53
415682,eet8jFl-FrSbsJfLCFC1EA,I-KFzdnJcqbUHOAdO2I7Ig,0,2013-08-09 01:38:17
416100,gGIbgz9b8BO4FKeEygmfhA,SycRVheLdFcK-2jt8j5d4Q,0,2012-06-27 01:36:45
416135,FtdW5kxnDwYZ0h23WUx8Yw,EIH5pDc75v4haOcww-SEJg,0,2017-02-16 18:18:10

In [1714]:
df_conseils[df_conseils.duplicated(subset=['utilisateur_id', 'restaurant_id', 'date'], keep=False)]

,utilisateur_id,restaurant_id,nb_compliments,date
1257,rt3PC7WCgCKsoufmQJELfw,CWNMLT-ppaUjLMmrnYDPVg,0,2010-12-14 00:53:04
19300,d_IFkIwz3jzt6yRIpTttsQ,DvY_J2gFxudK9HC8kjI3NA,0,2012-06-15 19:10:09
22872,uv5F82-AVlSr8-BFswTUWQ,lmfyEVKm3CDGWg18LeRhgA,0,2011-08-06 02:35:08
26309,3CGGvC-FAfo0AMwGVDrkNQ,XXW_OFaYQkkGOGniujZFHg,0,2012-01-10 00:06:16
31396,ifflfwmK6C7Fd7_7luevvQ,84ezTxVxTCmI65_UeYRJcA,0,2017-09-24 19:41:03
...,...,...,...,...
411011,4qvl4SkzJDQ-t4hGd0IlLg,_U4M_X9y3Jg2092XjuzSkw,0,2014-11-22 01:20:02
411208,bKB3fzqTMCIHLNvhWAWf1Q,S_F4XmLUZFv9Uzbjy44_NA,0,2017-07-04 21:19:07
412117,bKB3fzqTMCIHLNvhWAWf1Q,S_F4XmLUZFv9Uzbjy44_NA,0,2017-07-04 21:19:07
412538,4qvl4SkzJDQ-t4hGd0IlLg,_U4M_X9y3Jg2092XjuzSkw,0,2014-11-22 01:20:02
413431,A_GGpNX1NBettgTeZWqUrg,X-WXPGYuuknAjZkpYGeRiw,0,2017-10-22 22:36:57

In [1715]:
df_conseils[df_conseils.duplicated(subset=['utilisateur_id', 'restaurant_id', 'nb_compliments', 'date'], keep=False)].sort_values(by=['utilisateur_id', 'restaurant_id', 'nb_compliments', 'date'])
    # Beaucoup de doublons trouvés

,utilisateur_id,restaurant_id,nb_compliments,date
316741,-LuuXQ2ik3Ra4RiAdWyvdA,i066yR2IDP4FWt6p-k9aFg,0,2014-12-12 04:25:36
319039,-LuuXQ2ik3Ra4RiAdWyvdA,i066yR2IDP4FWt6p-k9aFg,0,2014-12-12 04:25:36
68500,3CGGvC-FAfo0AMwGVDrkNQ,GHS1rVjO-RMcRB6WJLpCDQ,0,2011-11-26 20:49:56
117459,3CGGvC-FAfo0AMwGVDrkNQ,GHS1rVjO-RMcRB6WJLpCDQ,0,2011-11-26 20:49:56
26309,3CGGvC-FAfo0AMwGVDrkNQ,XXW_OFaYQkkGOGniujZFHg,0,2012-01-10 00:06:16
...,...,...,...,...
69696,uv5F82-AVlSr8-BFswTUWQ,lmfyEVKm3CDGWg18LeRhgA,0,2011-08-06 02:35:08
214499,wfzJho9yA3Io_DoSlpDiVg,0XEqyl_lVaJNHRKxNcjJZg,0,2014-04-06 00:32:01
229744,wfzJho9yA3Io_DoSlpDiVg,0XEqyl_lVaJNHRKxNcjJZg,0,2014-04-06 00:32:01
64820,y05H_1uQhO4frLTJ5_tGCQ,JTo0oS3iiMl6UPWA6aI8SQ,0,2016-02-09 01:29:30
97167,y05H_1uQhO4frLTJ5_tGCQ,JTo0oS3iiMl6UPWA6aI8SQ,0,2016-02-09 01:29:30

In [1716]:
df_conseils.isna().sum()

utilisateur_id    0
restaurant_id     0
nb_compliments    0
date              0
dtype: int64

In [1717]:
df_conseils[(df_conseils['utilisateur_id'] == '') | (df_conseils['restaurant_id'] == '')]

Empty DataFrame
Columns: [utilisateur_id, restaurant_id, nb_compliments, date]
Index: []

### Nettoyage :

In [1718]:
# Suppression des doublons
df_conseils = df_conseils.drop_duplicates(subset=['utilisateur_id', 'restaurant_id', 'date']).copy()
df_conseils[df_conseils.duplicated(subset=['utilisateur_id', 'restaurant_id', 'date'], keep=False)]

Empty DataFrame
Columns: [utilisateur_id, restaurant_id, nb_compliments, date]
Index: []

In [1719]:
# Conversion vers les types appropriés
df_conseils['utilisateur_id'] = df_conseils['utilisateur_id'].astype('string')
df_conseils['restaurant_id'] = df_conseils['restaurant_id'].astype('string')
df_conseils['date'] = pd.to_datetime(df_conseils['date'], errors='coerce')
df_conseils.info()

<class 'pandas.core.frame.DataFrame'>
Index: 416752 entries, 0 to 416802
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   utilisateur_id  416752 non-null  string
 1   restaurant_id   416752 non-null  string
 2   nb_compliments  416752 non-null  int64
 3   date            416752 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), string(2)
memory usage: 15.9 MB

### Dataset nettoyé :

In [1720]:
df_conseils

,utilisateur_id,restaurant_id,nb_compliments,date
0,UPw5DWs_b-e2JRBS-t37Ag,VaKXUpmWTTWDKbpJ3aQdMw,0,2014-03-27 03:51:24
1,jRyO2V1pA4CdVVqCIOPc1Q,5KheTjYPu1HcQzQFtm4_vw,0,2011-12-26 01:46:17
2,FuTJWFYm4UKqewaosss1KA,TkoyGi8J7YFjA6SbaRzrxg,0,2014-03-23 21:32:49
3,CaFbX7topxdLpBJ_SNDfGQ,r49iBfbnfoK7yt4rdsL_7g,0,2016-01-05 06:39:33
4,8zXgNCkusOHMwh5Tj_8yCQ,qrSsS0pk7SL67MP5nN8tlg,0,2013-12-22 05:10:12
...,...,...,...,...
416798,yx_38-qpzJU2Oqb5P3QBqA,ZeeWNTA3wpabS_0Y1We7DA,0,2018-05-07 18:32:24
416799,Lu7d-uVVEYZrmxtX0gI8hQ,3GEEy7RP6e4bT4LAiWFMFQ,0,2018-05-16 14:47:50
416800,cHaCQ03WO3OWNmySffQprw,y-ZZe1dz8AMjiAwNVo3h_A,0,2018-06-26 22:14:05
416801,mkbx55W8B8aPLgDqex7qgg,OMRYQihVjqqzjoNoQgyhgQ,2,2017-11-10 15:34:58
416802,T4R5ZKfcGt1GIAgjCh67eA,n5Hc_iMVkyxcS0SXiBCbOQ,0,2018-10-13 16:57:50

---

## Horaires

### Vérifications :

In [1721]:
df_horaires
    # Plusieurs NaN à gérer 
        # peut interpréter NaN comme une journée fermée
        # sauf si c'est toute la semaine
            # données manquantes ou un commerce en faillite?

,restaurant_id,lundi,mardi,mercredi,jeudi,vendredi,samedi,dimanche
0,lCwqJWMxvIUQt1Re_tDn4w,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
1,pd0v6sOqpLhFJ7mkpIaixw,11:0-20:0,11:0-20:0,11:0-20:0,11:0-20:0,11:0-22:0,11:0-22:0,11:0-17:0
2,0vhi__HtC2L4-vScgDFdFw,11:30-22:0,11:30-22:0,11:30-22:0,11:30-22:0,11:30-22:0,12:0-22:0,16:30-21:30
3,t65yfB9v9fqlhAkLnnUXdg,11:30-21:0,11:30-21:0,11:30-21:0,11:30-21:0,11:30-21:0,NaN,11:30-21:0
4,i7_JPit-2kAbtRTLkic2jA,11:30-22:0,11:30-22:0,11:30-23:0,11:30-23:0,11:30-23:0,NaN,NaN
...,...,...,...,...,...,...,...,...
34263,cjZfgcQwA6KmQ_ANWKN2aw,NaN,5:30-15:0,5:30-15:0,5:30-15:0,5:30-15:0,6:0-15:0,6:0-15:0
34264,Hq2edcOTjse7wjK2CwBijQ,11:30-21:0,11:30-21:0,11:30-21:0,11:30-21:0,11:30-22:0,11:30-22:0,11:30-21:0
34265,7KlpgRjjAmVabPzxcExs0g,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34266,0fY-zYyP2fDmp2YXFsuNTg,NaN,7:0-14:0,7:0-14:0,7:0-14:0,7:0-14:0,7:0-14:0,NaN
34267,cfrN6-lQC-dzjBtNBjefpQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1722]:
df_horaires.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34268 entries, 0 to 34267
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   restaurant_id  34268 non-null  object
 1   lundi          22020 non-null  object
 2   mardi          23939 non-null  object
 3   mercredi       24498 non-null  object
 4   jeudi          24654 non-null  object
 5   vendredi       24695 non-null  object
 6   samedi         23994 non-null  object
 7   dimanche       20552 non-null  object
dtypes: object(8)
memory usage: 2.1+ MB

In [1723]:
df_horaires.describe(include='all')

,restaurant_id,lundi,mardi,mercredi,jeudi,vendredi,samedi,dimanche
count,34268,22020,23939,24498,24654,24695,23994,20552
unique,34268,715,730,744,759,805,826,747
top,lCwqJWMxvIUQt1Re_tDn4w,0:0-0:0,11:0-22:0,11:0-22:0,11:0-22:0,11:0-22:0,11:0-22:0,11:0-22:0
freq,1,2257,2444,2489,2437,1979,1649,1463

In [1724]:
df_horaires[(df_horaires['restaurant_id'] == '')]

Empty DataFrame
Columns: [restaurant_id, lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche]
Index: []

In [1725]:
df_horaires.isna().sum()

restaurant_id        0
lundi            12248
mardi            10329
mercredi          9770
jeudi             9614
vendredi          9573
samedi           10274
dimanche         13716
dtype: int64

In [1726]:
# Vérification du nombre de restaurants sans horaires (fermés?)
jours = ['lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche']
df_horaires[(df_horaires[jours] == '0:0-0:0').all(axis=1)]

,restaurant_id,lundi,mardi,mercredi,jeudi,vendredi,samedi,dimanche
0,lCwqJWMxvIUQt1Re_tDn4w,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
56,hmL0KnYU6F9_egjlLmizKA,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
63,QhMhM3Mhokv6V-H0MRuYTg,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
74,qbCPF1Z-Dher2MYUYFCX4Q,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
107,Lyn5sYu1rfxdmntbaOoZJg,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
...,...,...,...,...,...,...,...,...
33701,v6YvYMjxMMS3L-UQe5WAiQ,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
33739,Pnf2HbEcfZ4POhBUSUTq6Q,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
33751,68_nIoStgS3XUoZiW6doAg,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
33903,tlZmJBQ9UWkaI0Zce_KFhg,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
33940,BOMgSyi4-TYAnjVn3m0z3A,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0

In [1727]:
# Vérification du nombre de restaurants sans horaires (avec des NaN)
df_horaires[(df_horaires[jours].isna()).all(axis=1)]

,restaurant_id,lundi,mardi,mercredi,jeudi,vendredi,samedi,dimanche
5,vMh4madPU3qhNX7P7d8WGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Xb7jOAa17xtT_uA4sCCAsg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,4ScLXRii_WwBn5PbGBI-eg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,LAswzVTnT3uCvnKr-SwxEg,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,wfiKgzubn1cnVUBODsoJ_w,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
34257,9NUZao5_Jfhj5H45H0ccOQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34259,z0nVjbfDw8eb7N57HWNg8w,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34261,ckc3l8cSuggloG4NlquEFQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34265,7KlpgRjjAmVabPzxcExs0g,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34267,cfrN6-lQC-dzjBtNBjefpQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Nettoyage :

In [1728]:
# Convertir les NaN en 0:0-0:0 pour signifier une fermeture ou horaire manquant
df_horaires[jours] = df_horaires[jours].fillna('0:0-0:0')
df_horaires[(df_horaires[jours].isna()).all(axis=1)]

Empty DataFrame
Columns: [restaurant_id, lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche]
Index: []

In [1729]:
# Conversion vers le types approprié
df_horaires['restaurant_id'] = df_horaires['restaurant_id'].astype('string')
df_horaires[jours] = df_horaires[jours].astype('string')
df_horaires.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34268 entries, 0 to 34267
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   restaurant_id  34268 non-null  string
 1   lundi          34268 non-null  string
 2   mardi          34268 non-null  string
 3   mercredi       34268 non-null  string
 4   jeudi          34268 non-null  string
 5   vendredi       34268 non-null  string
 6   samedi         34268 non-null  string
 7   dimanche       34268 non-null  string
dtypes: string(8)
memory usage: 2.1 MB

In [1730]:
df_horaires.isna().sum()

restaurant_id    0
lundi            0
mardi            0
mercredi         0
jeudi            0
vendredi         0
samedi           0
dimanche         0
dtype: int64

### Dataset nettoyé :

In [1731]:
df_horaires

,restaurant_id,lundi,mardi,mercredi,jeudi,vendredi,samedi,dimanche
0,lCwqJWMxvIUQt1Re_tDn4w,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
1,pd0v6sOqpLhFJ7mkpIaixw,11:0-20:0,11:0-20:0,11:0-20:0,11:0-20:0,11:0-22:0,11:0-22:0,11:0-17:0
2,0vhi__HtC2L4-vScgDFdFw,11:30-22:0,11:30-22:0,11:30-22:0,11:30-22:0,11:30-22:0,12:0-22:0,16:30-21:30
3,t65yfB9v9fqlhAkLnnUXdg,11:30-21:0,11:30-21:0,11:30-21:0,11:30-21:0,11:30-21:0,0:0-0:0,11:30-21:0
4,i7_JPit-2kAbtRTLkic2jA,11:30-22:0,11:30-22:0,11:30-23:0,11:30-23:0,11:30-23:0,0:0-0:0,0:0-0:0
...,...,...,...,...,...,...,...,...
34263,cjZfgcQwA6KmQ_ANWKN2aw,0:0-0:0,5:30-15:0,5:30-15:0,5:30-15:0,5:30-15:0,6:0-15:0,6:0-15:0
34264,Hq2edcOTjse7wjK2CwBijQ,11:30-21:0,11:30-21:0,11:30-21:0,11:30-21:0,11:30-22:0,11:30-22:0,11:30-21:0
34265,7KlpgRjjAmVabPzxcExs0g,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0
34266,0fY-zYyP2fDmp2YXFsuNTg,0:0-0:0,7:0-14:0,7:0-14:0,7:0-14:0,7:0-14:0,7:0-14:0,0:0-0:0
34267,cfrN6-lQC-dzjBtNBjefpQ,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0,0:0-0:0

---

## Restaurants

### Vérifications :

In [1732]:
df_restaurants

,restaurant_id,nom,moyenne_etoiles,ville,zone,ferme
0,lCwqJWMxvIUQt1Re_tDn4w,Denny's,2.5,Las Vegas,89110,0
1,pd0v6sOqpLhFJ7mkpIaixw,Ike's Love & Sandwiches,4.0,Phoenix,85004,0
2,0vhi__HtC2L4-vScgDFdFw,Midori Japanese Cafe,3.5,Calgary,T2T,0
3,t65yfB9v9fqlhAkLnnUXdg,Pho U,3.5,Toronto,M5A,0
4,i7_JPit-2kAbtRTLkic2jA,John & Sons Oyster House,4.0,Toronto,M5H,0
...,...,...,...,...,...,...
34263,cjZfgcQwA6KmQ_ANWKN2aw,Bruegger's Bagels,3.5,McMurray,15317,1
34264,Hq2edcOTjse7wjK2CwBijQ,Bistro Pointe-Claire,3.5,Pointe-Claire,H9S,1
34265,7KlpgRjjAmVabPzxcExs0g,Taco Mex,4.0,Phoenix,85051,1
34266,0fY-zYyP2fDmp2YXFsuNTg,Gotham Provisions Company,4.0,Sun Prairie,53590,1
34267,cfrN6-lQC-dzjBtNBjefpQ,Rusty Nail Banquet Hall,2.5,Kent,44240,1

In [1733]:
df_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34268 entries, 0 to 34267
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   restaurant_id    34268 non-null  object
 1   nom              34268 non-null  object
 2   moyenne_etoiles  34268 non-null  float64
 3   ville            34268 non-null  object
 4   zone             34201 non-null  object
 5   ferme            34268 non-null  int64
dtypes: float64(1), int64(1), object(4)
memory usage: 1.6+ MB

In [1734]:
df_restaurants.describe(include='all')
    # Tous les ID sont uniques

,restaurant_id,nom,moyenne_etoiles,ville,zone,ferme
count,34268,34268,34268.000000,34268,34201,34268.000000
unique,34268,26024,NaN,614,970,NaN
top,lCwqJWMxvIUQt1Re_tDn4w,McDonald's,NaN,Toronto,89109,NaN
freq,1,382,NaN,4847,573,NaN
mean,NaN,NaN,3.430431,NaN,NaN,0.500000
std,NaN,NaN,0.792022,NaN,NaN,0.500007
min,NaN,NaN,1.000000,NaN,NaN,0.000000
25%,NaN,NaN,3.000000,NaN,NaN,0.000000
50%,NaN,NaN,3.500000,NaN,NaN,0.500000
75%,NaN,NaN,4.000000,NaN,NaN,1.000000
max,NaN,NaN,5.000000,NaN,NaN,1.000000

In [1735]:
df_restaurants[df_restaurants['restaurant_id'] == '']

Empty DataFrame
Columns: [restaurant_id, nom, moyenne_etoiles, ville, zone, ferme]
Index: []

In [1736]:
df_restaurants.isna().sum()

restaurant_id       0
nom                 0
moyenne_etoiles     0
ville               0
zone               67
ferme               0
dtype: int64

In [1737]:
df_restaurants[df_restaurants['zone'].isna()]

,restaurant_id,nom,moyenne_etoiles,ville,zone,ferme
46,NrztAypJHgPcevJNC_VOGg,Bandit Burger,3.0,Calgary,NaN,0
313,dqzdumTXqMvoB7SVXos-Qg,Hodge Podge Truck,3.5,Cleveland,NaN,0
777,USGHcJS_Qpw32ngZEXrG_Q,Tandori Indian Cuisine,1.5,Calgary,NaN,0
1004,ZkT1IR8xBlfnKtApbV96Dg,Nana's Porch,5.0,Charlotte,NaN,0
1081,YBec-htc0Obt3_o2BkRbVA,Caplansky's Thunderin' Thelma,3.0,Toronto,NaN,0
...,...,...,...,...,...,...
23205,qzbbz8QaoPsAlXEsjgtusg,Weekender Cafe,4.0,Whitchurch-Stouffville,NaN,1
24448,m4pZSpO8v84IlsGjqHXBaQ,Mobile Waiters,3.5,Phoenix,NaN,1
25534,VRKJpWhQeUE_38jnKrgsrA,ROKs Tacos - Korean BBQ Tacos,3.0,Champaign,NaN,1
29746,iTCH7y2KLRMKMxdEkgUK1g,Street Dogs,4.5,Las Vegas,NaN,1
30448,CCZrbW_8majCaFqni_OasA,Epazote & Haricot,4.5,Saint-Lazare,NaN,1

In [1738]:
# Vérification s'il existe des données autres que 1 ou 0
df_restaurants[(df_restaurants['ferme'] != 1) & (df_restaurants['ferme'] != 0)]

Empty DataFrame
Columns: [restaurant_id, nom, moyenne_etoiles, ville, zone, ferme]
Index: []

In [1739]:
# Vérification s'il existe des moyennes hors de 1.0 à 5.0
df_restaurants[(df_restaurants['moyenne_etoiles'] < 1.0) | (df_restaurants['moyenne_etoiles'] > 5.0)]

Empty DataFrame
Columns: [restaurant_id, nom, moyenne_etoiles, ville, zone, ferme]
Index: []

### Nettoyage :

In [1740]:
# Suppression de colonne non-utilisée
df_restaurants = df_restaurants.drop(columns=['zone'])

In [1741]:
# Conversion vers le types approprié
df_restaurants['restaurant_id'] = df_restaurants['restaurant_id'].astype('string')
df_restaurants['nom'] = df_restaurants['nom'].astype('string')
df_restaurants['ville'] = df_restaurants['ville'].astype('string')
df_restaurants['ferme'] = df_restaurants['ferme'].astype(bool)
df_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34268 entries, 0 to 34267
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   restaurant_id    34268 non-null  string
 1   nom              34268 non-null  string
 2   moyenne_etoiles  34268 non-null  float64
 3   ville            34268 non-null  string
 4   ferme            34268 non-null  bool
dtypes: bool(1), float64(1), string(3)
memory usage: 1.1 MB

### Dataset nettoyé :

In [1742]:
df_restaurants

,restaurant_id,nom,moyenne_etoiles,ville,ferme
0,lCwqJWMxvIUQt1Re_tDn4w,Denny's,2.5,Las Vegas,False
1,pd0v6sOqpLhFJ7mkpIaixw,Ike's Love & Sandwiches,4.0,Phoenix,False
2,0vhi__HtC2L4-vScgDFdFw,Midori Japanese Cafe,3.5,Calgary,False
3,t65yfB9v9fqlhAkLnnUXdg,Pho U,3.5,Toronto,False
4,i7_JPit-2kAbtRTLkic2jA,John & Sons Oyster House,4.0,Toronto,False
...,...,...,...,...,...
34263,cjZfgcQwA6KmQ_ANWKN2aw,Bruegger's Bagels,3.5,McMurray,True
34264,Hq2edcOTjse7wjK2CwBijQ,Bistro Pointe-Claire,3.5,Pointe-Claire,True
34265,7KlpgRjjAmVabPzxcExs0g,Taco Mex,4.0,Phoenix,True
34266,0fY-zYyP2fDmp2YXFsuNTg,Gotham Provisions Company,4.0,Sun Prairie,True
34267,cfrN6-lQC-dzjBtNBjefpQ,Rusty Nail Banquet Hall,2.5,Kent,True

---

## Servies

### Vérifications :

In [1743]:
df_services

,restaurant_id,emporter,livraison,bon_pour_groupes,bon_pour_enfants,reservation,prix,terrasse
0,lCwqJWMxvIUQt1Re_tDn4w,1,0,1,1,0,2,0
1,pd0v6sOqpLhFJ7mkpIaixw,1,1,1,1,0,2,1
2,0vhi__HtC2L4-vScgDFdFw,1,0,0,1,1,2,1
3,t65yfB9v9fqlhAkLnnUXdg,1,1,0,1,1,1,0
4,i7_JPit-2kAbtRTLkic2jA,1,0,1,0,1,3,0
...,...,...,...,...,...,...,...,...
34263,cjZfgcQwA6KmQ_ANWKN2aw,1,0,1,1,0,1,0
34264,Hq2edcOTjse7wjK2CwBijQ,0,0,0,1,1,2,1
34265,7KlpgRjjAmVabPzxcExs0g,1,0,1,1,0,1,0
34266,0fY-zYyP2fDmp2YXFsuNTg,1,0,1,1,0,1,0
34267,cfrN6-lQC-dzjBtNBjefpQ,0,0,0,1,0,2,0

In [1744]:
df_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34268 entries, 0 to 34267
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   restaurant_id     34268 non-null  object
 1   emporter          34268 non-null  int64
 2   livraison         34268 non-null  int64
 3   bon_pour_groupes  34268 non-null  int64
 4   bon_pour_enfants  34268 non-null  int64
 5   reservation       34268 non-null  int64
 6   prix              34268 non-null  int64
 7   terrasse          34268 non-null  int64
dtypes: int64(7), object(1)
memory usage: 2.1+ MB

In [1745]:
df_services.describe(include='all')

,restaurant_id,emporter,livraison,bon_pour_groupes,bon_pour_enfants,reservation,prix,terrasse
count,34268,34268.000000,34268.000000,34268.000000,34268.000000,34268.000000,34268.000000,34268.000000
unique,34268,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,lCwqJWMxvIUQt1Re_tDn4w,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,0.810173,0.208737,0.742500,0.696335,0.343761,1.496557,0.326923
std,NaN,0.392170,0.406412,0.437263,0.459847,0.474969,0.805013,0.469096
min,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,NaN,1.000000,0.000000,1.000000,1.000000,0.000000,2.000000,0.000000
75%,NaN,1.000000,0.000000,1.000000,1.000000,1.000000,2.000000,1.000000
max,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.000000

In [1746]:
df_services.isna().sum()

restaurant_id       0
emporter            0
livraison           0
bon_pour_groupes    0
bon_pour_enfants    0
reservation         0
prix                0
terrasse            0
dtype: int64

In [1747]:
# Vérification s'il existe des données autres que 1 ou 0
df_services[(df_services['emporter'] != 1) & (df_services['emporter'] != 0) 
    | (df_services['livraison'] != 1) & (df_services['livraison'] != 0) 
    | (df_services['bon_pour_groupes'] != 1) & (df_services['bon_pour_groupes'] != 0) 
    | (df_services['bon_pour_enfants'] != 1) & (df_services['bon_pour_enfants'] != 0) 
    | (df_services['reservation'] != 1) & (df_services['reservation'] != 0) 
    | (df_services['terrasse'] != 1) & (df_services['terrasse'] != 0)]

Empty DataFrame
Columns: [restaurant_id, emporter, livraison, bon_pour_groupes, bon_pour_enfants, reservation, prix, terrasse]
Index: []

### Nettoyage :

In [1748]:
# Conversion vers le types approprié
df_services['restaurant_id'] = df_services['restaurant_id'].astype('string')
df_services['emporter'] = df_services['emporter'].astype(bool)
df_services['livraison'] = df_services['livraison'].astype(bool)
df_services['bon_pour_groupes'] = df_services['bon_pour_groupes'].astype(bool)
df_services['bon_pour_enfants'] = df_services['bon_pour_enfants'].astype(bool)
df_services['reservation'] = df_services['reservation'].astype(bool)
df_services['terrasse'] = df_services['terrasse'].astype(bool)
df_services.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34268 entries, 0 to 34267
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   restaurant_id     34268 non-null  string
 1   emporter          34268 non-null  bool
 2   livraison         34268 non-null  bool
 3   bon_pour_groupes  34268 non-null  bool
 4   bon_pour_enfants  34268 non-null  bool
 5   reservation       34268 non-null  bool
 6   prix              34268 non-null  int64
 7   terrasse          34268 non-null  bool
dtypes: bool(6), int64(1), string(1)
memory usage: 736.4 KB

---

## Utilisateurs

### Vérifications :

In [1749]:
df_utilisateurs

                utilisateur_id       nom  elite  nb_avis  nb_avis_mention
0       l6BmjZMeQD3rDxWUbiAiow    Rashmi      1       95               84
1       4XChL029mKr5hydo79Ljxg     Jenna      0       33               48
2       bc8C_eETBWL0olvFSJJd0w     David      0       16               28
3       MM4RJAeH6yuaN8oZDSt0RA     Nancy      1      361             1114
4       TEtzbpgA2BFBrC0y0sCbfw     Keane      1     1122            13311
...                        ...       ...    ...      ...              ...
748242  qIKRzgQwcLsRbcjFYD1jkg      Joel      0        3                0
748243  vyK8txmse-HVk7hAKCvuMQ     Keith      0       10                4
748244  gCfFBY-cO1Y0TxxKX89-ig  Maryorie      0        1                0
748245  Z2uEg8DIk1twiNC6NV7e9w   Adriana      0        1                1
748246  ib_elCBhGOamS0AALkh4Og       Lee      0        4                8

[748247 rows x 5 columns]

In [1750]:
df_utilisateurs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748247 entries, 0 to 748246
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   utilisateur_id   748247 non-null  object
 1   nom              748239 non-null  object
 2   elite            748247 non-null  int64
 3   nb_avis          748247 non-null  int64
 4   nb_avis_mention  748247 non-null  int64
dtypes: int64(3), object(2)
memory usage: 28.5+ MB

In [1751]:
df_utilisateurs.describe(include='all')
    # Tous des ID uniques
    # Minimum de 0 et maximum de 1 pour elite
    # Ne semble pas avoir des nombres négatifs

,utilisateur_id,nom,elite,nb_avis,nb_avis_mention
count,748247,748239,748247.000000,748247.00000,748247.000000
unique,748247,72126,NaN,NaN,NaN
top,l6BmjZMeQD3rDxWUbiAiow,John,NaN,NaN,NaN
freq,1,6668,NaN,NaN,NaN
mean,NaN,NaN,0.072799,34.38974,67.922637
std,NaN,NaN,0.259807,105.32548,667.026047
min,NaN,NaN,0.000000,0.00000,0.000000
25%,NaN,NaN,0.000000,3.00000,1.000000
50%,NaN,NaN,0.000000,9.00000,5.000000
75%,NaN,NaN,0.000000,24.00000,22.000000
max,NaN,NaN,1.000000,13278.00000,154202.000000

In [1752]:
df_utilisateurs.isna().sum()

utilisateur_id     0
nom                8
elite              0
nb_avis            0
nb_avis_mention    0
dtype: int64

In [1753]:
df_utilisateurs[df_utilisateurs['utilisateur_id'] == '']

Empty DataFrame
Columns: [utilisateur_id, nom, elite, nb_avis, nb_avis_mention]
Index: []

In [1754]:
# Vérification s'il existe des données autres que 1 ou 0
df_utilisateurs[(df_utilisateurs['elite'] != 1) & (df_utilisateurs['elite'] != 0)]

Empty DataFrame
Columns: [utilisateur_id, nom, elite, nb_avis, nb_avis_mention]
Index: []

In [1755]:
# Vérification s'il existe des nombres négatifs
df_utilisateurs[df_utilisateurs['nb_avis'] < 0]

Empty DataFrame
Columns: [utilisateur_id, nom, elite, nb_avis, nb_avis_mention]
Index: []

In [1756]:
# Vérification s'il existe des nombres négatifs
df_utilisateurs[df_utilisateurs['nb_avis_mention'] < 0]

Empty DataFrame
Columns: [utilisateur_id, nom, elite, nb_avis, nb_avis_mention]
Index: []

In [1757]:
# Vérification s'il existe un ID dupliqué
df_utilisateurs['utilisateur_id'].duplicated().sum()

np.int64(0)

### Nettoyages :

In [1758]:
# Même si les noms sont manquants, on a les IDs et le nombre d'avis
df_utilisateurs['nom'] = df_utilisateurs['nom'].fillna('Inconnu')
df_utilisateurs[df_utilisateurs['nom'] == 'Inconnu']

                utilisateur_id      nom  elite  nb_avis  nb_avis_mention
87688   GiReVCFFK4WuhocoxDmOvw  Inconnu      0        5                0
161155  aahxmN1tsvlufuU_y4OT1A  Inconnu      0       23               61
207141  UgeQ4jZUvh8aknnOmvKRwg  Inconnu      0        9               11
237770  7UlRHLbYWR7RrIOp1pHDjw  Inconnu      1      486              945
245555  degkhE1YTY9x3Vt2OMEZbw  Inconnu      0       15               10
288643  OmBde8IjHEcO0QwS_jl5sA  Inconnu      0        9                3
369701  UxQyVv6m5N0Eb2hBp7VDqw  Inconnu      0        4                0
519971  nLJJAZM8CPA3W56cpZ9gxw  Inconnu      0        3                6

In [1759]:
# Conversion vers le types approprié
df_utilisateurs['utilisateur_id'] = df_utilisateurs['utilisateur_id'].astype('string')
df_utilisateurs['nom'] = df_utilisateurs['nom'].astype('string')
df_utilisateurs['elite'] = df_utilisateurs['elite'].astype(bool)
df_utilisateurs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748247 entries, 0 to 748246
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   utilisateur_id   748247 non-null  string
 1   nom              748247 non-null  string
 2   elite            748247 non-null  bool
 3   nb_avis          748247 non-null  int64
 4   nb_avis_mention  748247 non-null  int64
dtypes: bool(1), int64(2), string(2)
memory usage: 23.5 MB

### Dataset nettoyé :

In [1760]:
df_utilisateurs

                utilisateur_id       nom  elite  nb_avis  nb_avis_mention
0       l6BmjZMeQD3rDxWUbiAiow    Rashmi   True       95               84
1       4XChL029mKr5hydo79Ljxg     Jenna  False       33               48
2       bc8C_eETBWL0olvFSJJd0w     David  False       16               28
3       MM4RJAeH6yuaN8oZDSt0RA     Nancy   True      361             1114
4       TEtzbpgA2BFBrC0y0sCbfw     Keane   True     1122            13311
...                        ...       ...    ...      ...              ...
748242  qIKRzgQwcLsRbcjFYD1jkg      Joel  False        3                0
748243  vyK8txmse-HVk7hAKCvuMQ     Keith  False       10                4
748244  gCfFBY-cO1Y0TxxKX89-ig  Maryorie  False        1                0
748245  Z2uEg8DIk1twiNC6NV7e9w   Adriana  False        1                1
748246  ib_elCBhGOamS0AALkh4Og       Lee  False        4                8

[748247 rows x 5 columns]

---

# Création du Dataset `Business`

In [1782]:
df_business = df_restaurants[['restaurant_id', 'nom', 'ville', 'moyenne_etoiles']].rename(columns={'moyenne_etoiles': 'etoiles'})
review_count = df_avis.groupby('restaurant_id')['avis_id'].count().reset_index(name='review_count')
df_business = pd.merge(df_business, review_count, how='left', on='restaurant_id')
df_business = pd.merge(df_business, df_categories.groupby('restaurant_id')['categorie'].apply(lambda x: ', '.join(x.unique())).reset_index(), how='left', on='restaurant_id')
df_business = df_business.rename(columns={'restaurant_id': 'business_id'})
df_business

,business_id,nom,ville,etoiles,review_count,categorie
0,lCwqJWMxvIUQt1Re_tDn4w,Denny's,Las Vegas,2.5,72,"Breakfast & Brunch, Diners, American (Traditio..."
1,pd0v6sOqpLhFJ7mkpIaixw,Ike's Love & Sandwiches,Phoenix,4.0,108,"Sandwiches, Gluten-Free, Vegetarian, Vegan"
2,0vhi__HtC2L4-vScgDFdFw,Midori Japanese Cafe,Calgary,3.5,49,Japanese
3,t65yfB9v9fqlhAkLnnUXdg,Pho U,Toronto,3.5,36,"Vietnamese, Chinese"
4,i7_JPit-2kAbtRTLkic2jA,John & Sons Oyster House,Toronto,4.0,88,Seafood
...,...,...,...,...,...,...
34263,cjZfgcQwA6KmQ_ANWKN2aw,Bruegger's Bagels,McMurray,3.5,6,"Sandwiches, Breakfast & Brunch, Bagels"
34264,Hq2edcOTjse7wjK2CwBijQ,Bistro Pointe-Claire,Pointe-Claire,3.5,11,"Breakfast & Brunch, Canadian (New)"
34265,7KlpgRjjAmVabPzxcExs0g,Taco Mex,Phoenix,4.0,11,Mexican
34266,0fY-zYyP2fDmp2YXFsuNTg,Gotham Provisions Company,Sun Prairie,4.0,18,"Sandwiches, Soup, Bagels"
34267,cfrN6-lQC-dzjBtNBjefpQ,Rusty Nail Banquet Hall,Kent,2.5,3,American (New)

# Graphique statique